//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OficinaBDEntities : DbContext
    {
        public OficinaBDEntities()
            : base("name=OficinaBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbAtendente> tbAtendente { get; set; }
        public DbSet<tbCliente> tbCliente { get; set; }
        public DbSet<tbFornecedor> tbFornecedor { get; set; }
        public DbSet<tbLote> tbLote { get; set; }
        public DbSet<tbPedidoCliente> tbPedidoCliente { get; set; }
        public DbSet<tbPedidoFornecedor> tbPedidoFornecedor { get; set; }
        public DbSet<tbProduto> tbProduto { get; set; }
        public DbSet<tbVeiculo> tbVeiculo { get; set; }
    }
}
