//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLote
    {
        public int idPedidoFornecedor { get; set; }
        public string idProduto { get; set; }
        public string idFornecedor { get; set; }
        public string idAtendente { get; set; }
        public string quantidade { get; set; }
    }
}
