//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPedidoFornecedor
    {
        public int idPedidoCliente { get; set; }
        public string idProduto { get; set; }
        public string idCliente { get; set; }
        public string idLote { get; set; }
        public string idAtendente { get; set; }
        public string idPedidoFornecedor { get; set; }
        public string data { get; set; }
        public string quantidade { get; set; }
    }
}
