//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVeiculo
    {
        public int idVeiculo { get; set; }
        public string idCliente { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public string placa { get; set; }
        public string cor { get; set; }
    }
}
